name: PHP Codeception Tests - master

on:
  push:

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: cfiles
      use-rest-module: true
